package com.hyperlocal.notification.enums;

public enum EventType {
    NEW_ORDER,
    ORDER_STATUS_CHANGED,
    ORDER_ASSIGNED,
    ORDER_CANCELLED,
    NEW_DELIVERY,
    DELIVERY_ASSIGNED,
    DELIVERY_STATUS_CHANGED,
    DELIVERY_CANCELLED,
    DELIVERY_OFFER_CREATED,
    DELIVERY_OFFER_ACCEPTED,
    DELIVERY_OFFER_REJECTED,
    DELIVERY_OFFER_EXPIRED,
    DELIVERY_LOCATION_UPDATED
}
